
--------------------------------------------------APPLE RETAIL SALES PROJECT------------------------------------------------------------

--CREATING SCHEMA

DROP TABLE IF EXISTS STORES;

CREATE TABLE STORES(
STORE_ID VARCHAR(5) PRIMARY KEY,
STORE_NAME VARCHAR(30),
CITY VARCHAR(25),
COUNTRY VARCHAR(25)
);

DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE CATEGORY(
CATEGORY_ID VARCHAR(10) PRIMARY KEY,
CATEGORY_NAME VARCHAR(20)
);

DROP TABLE IF EXISTS PRODUCTS;

CREATE TABLE PRODUCTS(
PRODUCT_ID VARCHAR(10) PRIMARY KEY,
PRODUCT_NAME VARCHAR(35),
CATEGORY_ID VARCHAR(20),
LAUNCH_DATE DATE,
PRICE FLOAT
);
DROP TABLE IF EXISTS SALES;
CREATE TABLE SALES(
SALE_ID VARCHAR(15) PRIMARY KEY,
SALE_DATE DATE,
STORE_ID VARCHAR(10),
PRODUCT_ID VARCHAR(10),
QUANTITY INT,
CONSTRAINT FK_STORE FOREIGN KEY (STORE_ID) REFERENCES STORES(STORE_ID)
)
SELECT*
FROM STORES

DROP TABLE IF EXISTS WARANTY;

CREATE TABLE WARANTY(
CLAIM_ID VARCHAR(15),
CLAIM_DATE DATE,
SALE_ID VARCHAR(15),
REPAIR_STATUS VARCHAR(15),
CONSTRAINT FK_ORDERS FOREIGN KEY (SALE_ID) REFERENCES SALES(SALE_ID)
)

--IMPROVING QUERY PERFORMANCE

EXPLAIN ANALYZE
SELECT* FROM 
SALES
WHERE STORE_ID='ST-31'

--PLANNING TIME BEFORE INDEX=0.271ma
--EXECUTION TIME BEFORE INDEX=138.013ma

CREATE INDEX IND_SALES_ST ON SALES(SALE_ID);
CREATE INDEX IND_SALES_DT ON SALES(SALE_DATE);

EXPLAIN ANALYZE
SELECT* FROM 
SALES
WHERE STORE_ID='ST-31'

--PLANNING TIME BEFORE INDEX=0.171ma
--EXECUTION TIME BEFORE INDEX=128.098ma

--BUSINESS PROBLEMS

1--.Find the number of stores in each country.

SELECT COUNTRY,COUNT(*)
FROM STORES
GROUP BY 1
ORDER BY 2 DESC;

--2.Calculate the total number of units sold by each store.

SELECT ST.STORE_NAME,SUM(SS.QUANTITY)
FROM STORES ST INNER JOIN SALES SS
ON ST.STORE_ID=SS.STORE_ID
GROUP BY 1
ORDER BY 2 DESC;

--3.Identify how many sales occurred in December 2023.\

SELECT COUNT(*)
FROM SALES
WHERE SALE_DATE BETWEEN '01-12-2023' AND '31-12-2023';

--4.Determine how many stores have never had a warranty claim filed.

SELECT STORE_ID 
FROM STORES
WHERE STORE_ID NOT IN(
SELECT  ST.STORE_ID
FROM STORES ST INNER JOIN SALES SS 
ON SS.STORE_ID=ST.STORE_ID
INNER JOIN WARANTY W
ON W.SALE_ID=SS.SALE_ID);

--5.Calculate the percentage of warranty claims marked as "Rejected".

SELECT ROUND(COUNT(*)/(SELECT COUNT(*) FROM WARANTY)::NUMERIC*100,1)||'%' AS PRECENTAGE
FROM WARANTY
WHERE REPAIR_STATUS='Rejected'

--6.Identify which store had the highest total units sold in the last year.

WITH HIGHEST AS(
SELECT SS.STORE_ID AS STORE_ID,SUM(SS.QUANTITY) SUM_SALES,
DENSE_RANK() OVER(ORDER BY SUM(SS.QUANTITY) DESC) AS DR
FROM SALES SS INNER JOIN STORES ST
ON ST.STORE_ID=SS.STORE_ID
GROUP BY SS.STORE_ID)
SELECT STORE_ID,SUM_SALES
FROM HIGHEST
WHERE DR=1

--7.Count the number of unique products sold in the last year.

SELECT COUNT( DISTINCT PRODUCT_ID)
FROM SALES
WHERE TO_CHAR(SALE_DATE,'YYYY')='2024'

--8.Find the average price of products in each category.

SELECT P.PRODUCT_NAME,AVG(P.PRICE)
FROM PRODUCTS P INNER JOIN CATEGORY C
ON C.CATEGORY_ID=P.CATEGORY_ID
GROUP BY P.PRODUCT_NAME

--9.How many warranty claims were filed in 2024?

SELECT COUNT(*)
FROM WARANTY
WHERE TO_CHAR(CLAIM_DATE,'YYYY')='2024' 

--10.For each store, identify the best-selling day based on highest quantity sold.

WITH DAT AS(
SELECT ST.STORE_NAME AS SN,SS.SALE_DATE AS SD,SUM(SS.QUANTITY) AS SQ,DENSE_RANK() OVER(PARTITION BY ST.STORE_NAME ORDER BY SUM(SS.QUANTITY) DESC) DR
FROM SALES SS INNER JOIN STORES ST
ON ST.STORE_ID=SS.STORE_ID
GROUP BY ST.STORE_NAME,SS.SALE_DATE
)
SELECT SN,SD
FROM DAT
WHERE DR=1;

--11.Identify the least selling product in each country for each year based on total units sold.
SELECT DISTINCT TO_CHAR(SALE_DATE,'YYYY')
FROM STORES INNER JOIN SALES S
ON STORES.STORE_ID=S.STORE_ID
;

WITH CT AS(
SELECT P.PRODUCT_NAME,ST.COUNTRY,TO_CHAR(SS.SALE_DATE,'YYYY')DAT,SUM(SS.QUANTITY),DENSE_RANK() OVER(PARTITION BY ST.COUNTRY,TO_CHAR(SS.SALE_DATE,'YYYY') ORDER BY SUM(SS.QUANTITY))DR
FROM SALES SS INNER JOIN STORES ST
ON SS.STORE_ID=ST.STORE_ID
INNER JOIN PRODUCTS P
ON P.PRODUCT_ID=SS.PRODUCT_ID
GROUP BY P.PRODUCT_NAME,ST.COUNTRY,TO_CHAR(SS.SALE_DATE,'YYYY')
)
SELECT PRODUCT_NAME,COUNTRY,DAT
FROM CT
WHERE DR=1;


--12.Calculate how many warranty claims were filed within 180 days of a product sale.

SELECT COUNT(*)
FROM WARANTY W INNER JOIN SALES S
ON S.SALE_ID=W.SALE_ID
WHERE CLAIM_DATE>=SALE_DATE-INTERVAL '180 DAYS'

--13.Determine how many warranty claims were filed for products launched in the last two years.

SELECT COUNT(*)
FROM WARANTY
WHERE CLAIM_DATE>=CLAIM_DATE-INTERVAL '2 YEARS'

--14.List the months in the last three years where sales exceeded 5,000 units in the USA.

SELECT DISTINCT TO_CHAR(SS.SALE_DATE,'MON')
FROM PRODUCTS P INNER JOIN SALES SS
ON P.PRODUCT_ID=SS.PRODUCT_ID
INNER JOIN STORES ST
ON ST.STORE_ID=SS.STORE_ID
WHERE SALE_DATE>=SALE_DATE-INTERVAL '3 YEARS'
GROUP BY TO_CHAR(SS.SALE_DATE,'MON')
HAVING SUM(P.PRICE*SS.QUANTITY)>5000

--15.Identify the product category with the most warranty claims filed in the last two years.

WITH WAR AS(
SELECT P.CATEGORY_ID,RANK() OVER(ORDER BY COUNT(*) DESC)R
FROM SALES S INNER JOIN PRODUCTS P
ON P.PRODUCT_ID=S.PRODUCT_ID
INNER JOIN WARANTY W
ON S.SALE_ID=W.SALE_ID
GROUP BY P.CATEGORY_ID
ORDER BY 2)
SELECT CATEGORY_ID
FROM WAR 
WHERE R=1

--16.Determine the percentage chance of receiving warranty claims after each purchase for each country.
WITH PERCENTAGE AS(
SELECT ST.COUNTRY,COUNT(*)CT
FROM STORES ST INNER JOIN SALES SS
ON SS.STORE_ID=ST.STORE_ID
INNER JOIN WARANTY W
ON W.SALE_ID=SS.SALE_ID
GROUP BY ST.COUNTRY),
TOTAL AS(
SELECT COUNTRY,SUM(SALES.QUANTITY)CT
FROM STORES INNER JOIN SALES 
ON SALES.STORE_ID=STORES.STORE_ID
GROUP BY COUNTRY
)
SELECT P.COUNTRY,ROUND(P.CT/T.CT::NUMERIC*100,1)||'%' AS PERCENTAGE
FROM PERCENTAGE P INNER JOIN TOTAL T
ON T.COUNTRY=P.COUNTRY


--17.Analyze the year-by-year growth ratio for each store.

WITH INCOME AS(
SELECT ST.STORE_NAME,EXTRACT(YEAR FROM SS.SALE_DATE)DATTE,SUM(SS.QUANTITY*P.PRICE) AS REVENUE,
LAG(SUM(SS.QUANTITY*P.PRICE)) OVER(PARTITION BY ST.STORE_NAME ORDER BY EXTRACT(YEAR FROM SS.SALE_DATE))PRE_YEAR
FROM STORES ST INNER JOIN SALES SS
ON SS.STORE_ID=ST.STORE_ID
INNER JOIN PRODUCTS P
ON P.PRODUCT_ID=SS.PRODUCT_ID
GROUP BY ST.STORE_NAME,EXTRACT(YEAR FROM SS.SALE_DATE))
SELECT STORE_NAME,DATTE,ROUND(COALESCE(REVENUE/PRE_YEAR)::NUMERIC,2)RATIO
FROM INCOME

--18.Calculate the correlation between product price and warranty claims for products sold in the last five years, segmented by price range.

WITH PRODUCT_CLAIMS AS(
SELECT P.PRODUCT_ID,P.PRICE,COUNT(W.CLAIM_ID) AS W_CLAIMS
FROM SALES SS INNER JOIN STORES ST
ON ST.STORE_ID=SS.STORE_ID
INNER JOIN PRODUCTS P
ON P.PRODUCT_ID=SS.PRODUCT_ID
INNER JOIN WARANTY W
ON W.SALE_ID=SS.SALE_ID
WHERE SS.SALE_DATE>=SS.SALE_DATE-INTERVAL '5 YEARS'
GROUP BY  P.PRODUCT_ID,P.PRICE),
PRICE_RANGE AS(
SELECT PRICE,W_CLAIMS,
CASE
WHEN price < 600 THEN 'LOW'
WHEN price < 1200 THEN 'MEDIUM'
ELSE 'HIGH'
END AS price_range
FROM PRODUCT_CLAIMS
)
SELECT PRICE_RANGE,CORR(PRICE,W_CLAIMS)
FROM PRICE_RANGE
GROUP BY PRICE_RANGE

--19.Identify the store with the highest percentage of "PENDING" claims relative to total claims filed.

WITH TOTAL_CLAIMS AS(
SELECT ST.STORE_NAME,COUNT(W.CLAIM_ID)TCNT
FROM STORES ST INNER JOIN SALES SS
ON ST.STORE_ID=SS.STORE_ID
INNER JOIN WARANTY W
ON W.SALE_ID=SS.SALE_ID
GROUP BY ST.STORE_NAME),
PENDING_CLAIMS AS(
SELECT ST.STORE_NAME,COUNT(W.CLAIM_ID)PCNT
FROM STORES ST INNER JOIN SALES SS
ON ST.STORE_ID=SS.STORE_ID
INNER JOIN WARANTY W
ON W.SALE_ID=SS.SALE_ID
WHERE REPAIR_STATUS='Pending'
GROUP BY ST.STORE_NAME
),
RANKING AS(
SELECT PC.STORE_NAME,ROUND(PC.PCNT/TC.TCNT::NUMERIC*100,2)PERC,RANK() OVER(ORDER BY ROUND(PC.PCNT/TC.TCNT::NUMERIC*100,2) DESC)RAN
FROM PENDING_CLAIMS PC INNER JOIN TOTAL_CLAIMS TC
ON TC.STORE_NAME=PC.STORE_NAME)
SELECT STORE_NAME,PERC||'%'
FROM RANKING
WHERE RAN=1

--20.Write a query to calculate the monthly running total of sales for each store over the past four years and compare trends during this period.
WITH SALES AS(
SELECT ST.STORE_NAME,DATE_TRUNC('MONTH',SALE_DATE)DD,SUM(P.PRICE*SS.QUANTITY)CR_REVENUE
FROM SALES SS INNER JOIN PRODUCTS P
ON P.PRODUCT_ID=SS.PRODUCT_ID
INNER JOIN STORES ST
ON ST.STORE_ID=SS.STORE_ID
WHERE SS.SALE_DATE>=CURRENT_DATE-INTERVAL '4 YEARS'
GROUP BY 1,2)
SELECT STORE_NAME,DD,CR_REVENUE,
SUM(CR_REVENUE) OVER(PARTITION BY STORE_NAME ORDER BY DD)
FROM SALES

--Analyze product sales trends over time, segmented into key periods: from launch to 6 months, 6-12 months, 12-18 months, and beyond 18 months.

SELECT*
FROM PRODUCTS;
WITH PROD AS(
SELECT P.PRODUCT_NAME,SS.SALE_DATE,P.LAUNCH_DATE,P.PRICE,SS.QUANTITY
FROM PRODUCTS P INNER JOIN SALES SS
ON SS.PRODUCT_ID=P.PRODUCT_ID)
SELECT PRODUCT_NAME,
SUM(
CASE
WHEN SALE_DATE >= LAUNCH_DATE AND SALE_DATE < LAUNCH_DATE + INTERVAL '6 MONTHS' THEN 'FIRST_6_MONTHS'
ELSE 0
END
)FIRST_6_MONTHS,
SUM(
CASE
WHEN SALE_DATE>=LAUNCH_DATE +INTERVAL '6 MONTHS' AND SALE_DATE<=LAUNCH_DATE+INTERVAL '12 MONTHS' THEN PRICE*QUANTITY
ELSE 0
END
)SIX_TO_12_MONTHS,
SUM(
CASE
WHEN SALE_DATE>=LAUNCH_DATE +INTERVAL '12 MONTHS' AND SALE_DATE<=LAUNCH_DATE+INTERVAL '18 MONTHS' THEN PRICE*QUANTITY
ELSE 0
END
)TWELVE_TO_18_MONTHS,
SUM(
CASE
WHEN SALE_DATE>=LAUNCH_DATE+INTERVAL '18 MONTHS' THEN PRICE*QUANTITY
ELSE 0
END
)BEYOND_18_MONTHS
FROM PROD
GROUP BY PRODUCT_NAME
--SECOND APPROACH
WITH SALES AS(
SELECT P.PRODUCT_NAME,P.PRICE,S.QUANTITY,P.LAUNCH_DATE,S.SALE_DATE,
CASE
WHEN SALE_DATE >= LAUNCH_DATE
AND SALE_DATE < LAUNCH_DATE + INTERVAL '6 MONTHS'
THEN 'FIRST_6_MONTHS'
WHEN SALE_DATE >= LAUNCH_DATE + INTERVAL '6 MONTHS'
AND SALE_DATE < LAUNCH_DATE + INTERVAL '12 MONTHS'
THEN 'SIX_TO_12_MONTHS'
WHEN SALE_DATE >= LAUNCH_DATE + INTERVAL '12 MONTHS'
AND SALE_DATE < LAUNCH_DATE + INTERVAL '18 MONTHS'
THEN 'TWELVE_TO_18_MONTHS'
WHEN SALE_DATE >= LAUNCH_DATE + INTERVAL '18 MONTHS'
THEN 'BEYOND_18_MONTHS'
END AS RANGEE
FROM SALES S INNER JOIN PRODUCTS P
ON P.PRODUCT_ID=S.PRODUCT_ID)
SELECT PRODUCT_NAME,RANGEE,SUM(PRICE*QUANTITY)
FROM SALES
WHERE RANGEE IS NOT NULL
GROUP BY PRODUCT_NAME,RANGEE
ORDER BY 1,3 DESC



